In [82]:
import pandas as pd
import numpy as np
import spacy

In [83]:
import re

def nettoyer_phrase(phrase):
    phrase = phrase.strip()
    
   # uniformiser les tirets
    phrase = phrase.replace("–", "-").replace("—", "-")
    
    # enlever le tiret de dialogue en début
    phrase = re.sub(r"^\-\s*", "", phrase)
    
    # uniformiser les apostrophes
    phrase = phrase.replace("'", "’")
    
    # supprimer les espaces après une apostrophe élidée : s’ y -> s’y
    phrase = re.sub(r"([A-Za-zÀ-ÿ])’\s+([A-Za-zÀ-ÿ])", r"\1’\2", phrase)
    
    # espaces multiples
    phrase = re.sub(r"\s+", " ", phrase)
    
    return phrase.strip()

In [84]:
nlp = spacy.load("fr_core_news_lg")

In [85]:
# 1. Ouvrir le fichier et lire toutes les lignes d'un coup
with open("corpus_goncourt/1860_Charles Demailly_travail.txt", "r", encoding="utf-8") as f:
    lignes = f.readlines()

In [86]:
data = []

# 2. Boucler sur chaque ligne (qui est déjà une phrase)
for ligne in lignes:
    phrase_nettoyee = nettoyer_phrase(ligne) # Enlève les espaces et les \n invisibles
    
    if phrase_nettoyee: 
        data.append({
            'nom_fichier': "1860_Charles Demailly",
            'phrase': phrase_nettoyee
        })


df_final = pd.DataFrame(data)


print(f"Nombre de phrases chargées : {len(df_final)}")
df_final.head(10)

Nombre de phrases chargées : 1539

             nom_fichier                                             phrase
0  1860_Charles Demailly  Un article ?… Tu me demandes s’y a un article ...
1  1860_Charles Demailly                               Hein ! la société ?…
2  1860_Charles Demailly  Tu ne la connais pas ? C’est pourtant une soci...
3  1860_Charles Demailly                                            Après ?
4  1860_Charles Demailly  Après, après ? tu poses ta femme : une comédie...
5  1860_Charles Demailly  Ceci était dit dans une grande pièce tendue d’...
6  1860_Charles Demailly  y avait cinq hommes dans cette pièce qui était...
7  1860_Charles Demailly  L’un avait des cheveux blonds, le front court,...
8  1860_Charles Demailly  L’autre était un jeune homme de trente-quatre ...
9  1860_Charles Demailly  Des cheveux de femme, une bouche de femme, un ...

In [87]:
df_final["phrase"] = df_final["phrase"].astype(str).str.strip()
df_final = df_final[df_final["phrase"] != ""].copy()

In [88]:
def get_pos_pattern(phrase):
    doc = nlp(phrase)
    return " ".join([token.pos_ for token in doc])

df_final["motif_pos"] = df_final["phrase"].apply(get_pos_pattern)

In [89]:
df_final

,nom_fichier,phrase,motif_pos
0,1860_Charles Demailly,Un article ?… Tu me demandes s’y a un article ...,DET NOUN PUNCT PUNCT PRON PRON VERB PRON PRON ...
1,1860_Charles Demailly,Hein ! la société ?…,PROPN PUNCT DET NOUN PUNCT PUNCT
2,1860_Charles Demailly,Tu ne la connais pas ? C’est pourtant une soci...,PRON ADV DET NOUN ADV PUNCT PRON AUX ADV DET N...
3,1860_Charles Demailly,Après ?,ADP PUNCT
4,1860_Charles Demailly,"Après, après ? tu poses ta femme : une comédie...",ADP PUNCT ADP PUNCT PRON VERB DET NOUN PUNCT D...
...,...,...,...
1534,1860_Charles Demailly,Et ne répondit pas.,CCONJ ADV VERB ADV PUNCT
1535,1860_Charles Demailly,Nachette resta huit jours à Saint-Sauveur. fut...,PROPN VERB NUM NOUN ADP PROPN PUNCT AUX ADJ AD...
1536,1860_Charles Demailly,"Bref, Nachette amusa Marthe, désarma Charles, ...",ADV PUNCT PROPN VERB PROPN PUNCT VERB PROPN PU...
1537,1860_Charles Demailly,"Nachette parti, la campagne sembla à Marthe vi...",PROPN ADJ PUNCT DET NOUN VERB ADP PROPN NOUN A...
1538,1860_Charles Demailly,Montbaillard avait abonné le salon des eaux au...,ADV AUX VERB DET NOUN ADP NOUN ADP NOUN PUNCT ...

In [79]:
for phrase in df_final["phrase"].head(5):
    doc = nlp(phrase)
    print("\nPHRASE :", phrase)
    for token in doc:
        print(token.text, "->", token.pos_)

PHRASE : Un article ?… Tu me demandes s’y a un article dans mon histoire ? Mais, malheureux, un enfant de six ans en ferait une comédie en vers, les yeux bandés ! Scène première : le foyer de la Comédie-Française… tu comprends… la maison de Molière… Talma… les souvenirs… la tirade : c’est là où César cause avec Scapin, où Melpomène prend l’éventail de Thalie, où… où… où… n’y a pas de raison pour que ça finisse ! Tu passes aux indiscrétions : Provost et Anselme qui jouent aux échecs, l’ingénue qui demande une glace, l’huissier qui fait découvrir le grand-duc héréditaire de Toscane, et mademoiselle Fix qui le fait rougir de ne s’être point découvert de lui-même, la Société du rachat des captifs…
Un -> DET
article -> NOUN
? -> PUNCT
… -> PUNCT
Tu -> PRON
me -> PRON
demandes -> VERB
s’ -> PRON
y -> PRON
a -> VERB
un -> DET
article -> NOUN
dans -> ADP
mon -> DET
histoire -> NOUN
? -> PUNCT
Mais -> CCONJ
, -> PUNCT
malheureux -> ADJ
, -> PUNCT
un -> DET
enfant -> NOUN
de -> ADP
six -> NUM
ans -> NOUN
en -> ADP
ferait -> VERB
une -> DET
comédie -> NOUN
en -> ADP
vers -> ADP
, -> PUNCT
les -> DET
yeux -> NOUN
bandés -> ADJ
! -> PUNCT
Scène -> NOUN
première -> ADJ
: -> PUNCT
le -> DET
foyer -> NOUN
de -> ADP
la -> DET
Comédie -> PROPN
- -> PUNCT
Française -> ADJ
… -> PUNCT
tu -> PRON
comprends -> VERB
… -> PUNCT
la -> DET
maison -> NOUN
de -> ADP
Molière -> PROPN
… -> PUNCT
Talma -> PROPN
… -> PUNCT
les -> DET
souvenirs -> NOUN
… -> PUNCT
la -> DET
tirade -> NOUN
: -> PUNCT
c’ -> PRON
est -> AUX
là -> ADV
où -> PRON
César -> PROPN
cause -> NOUN
avec -> ADP
Scapin -> PROPN
, -> PUNCT
où -> PRON
Melpomène -> PROPN
prend -> VERB
l’ -> DET
éventail -> NOUN
de -> ADP
Thalie -> PROPN
, -> PUNCT
où -> PRON
… -> PUNCT
où -> PRON
… -> PUNCT
où -> PRON
… -> PUNCT
n’ -> ADV
y -> PRON
a -> VERB
pas -> ADV
de -> DET
raison -> NOUN
pour -> ADP
que -> SCONJ
ça -> PRON
finisse -> VERB
! -> PUNCT
Tu -> ADV
passes -> VERB
aux -> ADP
indiscrétions -> NOUN
: -> PUNCT
Provost -> PROPN
et -> CCONJ
Anselme -> PROPN
qui -> PRON
jouent -> VERB
aux -> ADP
échecs -> NOUN
, -> PUNCT
l’ -> DET
ingénue -> NOUN
qui -> PRON
demande -> VERB
une -> DET
glace -> NOUN
, -> PUNCT
l’ -> DET
huissier -> NOUN
qui -> PRON
fait -> AUX
découvrir -> VERB
le -> DET
grand-duc -> NOUN
héréditaire -> ADJ
de -> ADP
Toscane -> PROPN
, -> PUNCT
et -> CCONJ
mademoiselle -> PROPN
Fix -> PROPN
qui -> PRON
le -> PRON
fait -> NOUN
rougir -> VERB
de -> ADP
ne -> ADV
s’ -> PRON
être -> AUX
point -> NOUN
découvert -> VERB
de -> ADP
lui-même -> PRON
, -> PUNCT
la -> DET
Société -> PROPN
du -> ADP
rachat -> NOUN
des -> ADP
captifs -> NOUN
… -> PUNCT

PHRASE : Hein ! la société ?…
Hein -> PROPN
! -> PUNCT
la -> DET
société -> NOUN
? -> PUNCT
… -> PUNCT

PHRASE : Tu ne la connais pas ? C’est pourtant une société secrète… Devine ce qu’y a dans le foyer de la Comédie ?… y a des poulpes ! C’est terrible ! Une fois accroché, c’est fini ! ils vous entraînent au fond de leur conversation… Voilà, je suppose, un homme ou une femme, les poulpes n’y regardent pas, Got, si tu veux, ou mademoiselle Ricquier, pincés par Frappart ou par . Benett, l’auteur anglais… très bien ! Un membre de la Société accourt : Pardon ! j’aurais un mot à vous dire… - sauvé, mon Dieu ! dit l’autre… Et, voilà ce que c’est que la société du rachat des captifs !… Si tu ne fais pas cinquante lignes avec ça… Et puis y a des tableaux du foyer…
Tu -> PRON
ne -> ADV
la -> DET
connais -> NOUN
pas -> ADV
? -> PUNCT
C’ -> PRON
est -> AUX
pourtant -> ADV
une -> DET
société -> NOUN
secrète -> ADJ
… -> PUNCT
Devine -> NOUN
ce -> PRON
qu’ -> PRON
y -> PRON
a -> VERB
dans -> ADP
le -> DET
foyer -> NOUN
de -> ADP
la -> DET
Comédie -> NOUN
? -> PUNCT
… -> PUNCT
y -> PRON
a -> VERB
des -> DET
poulpes -> NOUN
! -> PUNCT
C’ -> PRON
est -> AUX
terrible -> ADJ
! -> PUNCT
Une -> DET
fois -> NOUN
accroché -> VERB
, -> PUNCT
c’ -> PRON
est -> AUX
fini -> VERB
! -> PUNCT
ils -> PRON
vous -> PRON
entraînent -> VERB
au -> ADP
fond -> NOUN
de -> ADP
leur -> DET
conversation -> NOUN
… -> PUNCT
Voilà -> VERB
, -> PUNCT
je -> PRON
suppose -> VERB
, -> PUNCT
un -> DET
homme -> NOUN
ou -> CCONJ
une -> DET
femme -> NOUN
, -> PUNCT
les -> DET
poulpes -> NOUN
n’ -> ADV
y -> PRON
regardent -> VERB
pas -> ADV
, -> PUNCT
Got -> PROPN
, -> PUNCT
si -> SCONJ
tu -> PRON
veux -> VERB
, -> PUNCT
ou -> CCONJ
mademoiselle -> PROPN
Ricquier -> PROPN
, -> PUNCT
pincés -> VERB
par -> ADP
Frappart -> PROPN
ou -> CCONJ
par -> ADP
. -> PUNCT
Benett -> PROPN
, -> PUNCT
l’ -> DET
auteur -> NOUN
anglais -> ADJ
… -> PUNCT
très -> ADV
bien -> ADV
! -> PUNCT
Un -> DET
membre -> NOUN
de -> ADP
la -> DET
Société -> PROPN
accourt -> VERB
: -> PUNCT
Pardon -> NOUN
! -> PUNCT
j’ -> PRON
aurais -> VERB
un -> DET
mot -> NOUN
à -> ADP
vous -> PRON
dire -> VERB
… -> PUNCT
- -> PUNCT
sauvé -> VERB
, -> PUNCT
mon -> DET
Dieu -> PROPN
! -> PUNCT
dit -> VERB
l’ -> DET
autre -> PRON
… -> PUNCT
Et -> CCONJ
, -> PUNCT
voilà -> VERB
ce -> PRON
que -> PRON
c’ -> PRON
est -> VERB
que -> SCONJ
la -> DET
société -> NOUN
du -> ADP
rachat -> NOUN
des -> ADP
captifs -> NOUN
! -> PUNCT
… -> PUNCT
Si -> SCONJ
tu -> PRON
ne -> ADV
fais -> VERB
pas -> ADV
cinquante -> NUM
lignes -> NOUN
avec -> ADP
ça -> PRON
… -> PUNCT
Et -> CCONJ
puis -> CCONJ
y -> PRON
a -> VERB
des -> DET
tableaux -> NOUN
du -> ADP
foyer -> NOUN
… -> PUNCT

PHRASE : Après ?
Après -> ADP
? -> PUNCT

PHRASE : Après, après ? tu poses ta femme : une comédienne célèbre… Tu ne la nommes pas… tu dis seulement : Notre Célimène… ça ne compromet personne !… Notre Célimène passait les mains dans les cheveux d’un grand poète… l’initiale du poète… faut toujours nommer un poète, sans ça on peut le confondre avec un homme qui fait des vers… Et tu entames le dialogue : « Ô mon poète ! - fait la Célimène, - pourquoi ne faites-vous plus de ces charmantes comédies comme vous seul savez en faire ?… Pour un rôle de vous où j’aurais quinze ans, je donnerais ans de ma vie !… » tu peux lâcher le mot : Célimène, vous y auriez gagné !… et tu passes au poète. Le poète a dîné ; a ronflé pendant une heure tout seul dans une loge de huit places ; est bu, mais bu… ferait un poème épique, et parle nègre ! Fais-le parler nègre, le public adore ça, ça lui rappelle Paul et Virginie ! - « Moi… pièce ?… moi… comédie ?… travailler ?… pas d’intérieur ?… impossible ! sale… rien trouver… brosses à dents partout !… travailler !… trop sale !… - Mais si quelqu’un vous installait dans un joli petit appartement bien rangé ? - Oh !… divin… pas de peignes sur les meubles… intérieur… plumes taillées… une pièce ! deux pièces !… trois pièces !… toujours ! - À demain matin… » - Et la comédienne serre la main du poète avec un sourire… tu trouveras le sourire ! Le poète est exact comme un billet. essaye un fauteuil : on y aurait dormi, - sans lire !… - Une table, du papier blanc, des plumes, de l’encre… - « S’y avait des cigares, soupire le poète, y aurait tout ce qu’faut pour écrire. » Célimène envoie chercher deux boîtes de cigares. L’heure du déjeuner arrive. « Ah ! tenez, - dit le poète, - faut que je quitte vos pantoufles… et puis je déjeunerai avec des amis… nous causerons… impossible… journée perdue ! - Mettez deux couverts, - fait Célimène à la cantonade, et se retournant : vous mangerez . Qu’aimez-vous ? - Tout, sauf le poulet rôti et le vin de Bordeaux. » Le soir nouvelles lamentations du poète : « Tenez ! Si je m’en vais chez moi, je n’arriverai que demain, je me lèverai après-demain… et… - Allons, voulez-vous que je vous fasse faire un lit dans le salon ? - Non, j’ai peur la nuit, et vous ?… » Bref, au bout de huit jours la pièce est faite. Elle est copiée. « Ah ! - crie tout à coup le poète, - un ruban !… un ruban pour l’amour de Dieu, un ruban pour l’amour de moi, me faut un de vos rubans ! Tenez, celui-là !… Oui, j’ai l’habitude comme cela de nouer mes manuscrits avec une jolie faveur… une idée… c’est bête… mais voilà. » Célimène donne le ruban, fait la rosette, et le poète court porter sa pièce à… parbleu ! à l’autre Célimène du Théâtre-Français ! Maintenant, toi, appelle ça : Roueries d’hommes, sers chaud, et - ça y est !
Après -> ADP
, -> PUNCT
après -> ADP
? -> PUNCT
tu -> PRON
poses -> VERB
ta -> DET
femme -> NOUN
: -> PUNCT
une -> DET
comédienne -> NOUN
célèbre -> ADJ
… -> PUNCT
Tu -> PRON
ne -> ADV
la -> PRON
nommes -> VERB
pas -> ADV
… -> PUNCT
tu -> PRON
dis -> VERB
seulement -> ADV
: -> PUNCT
Notre -> DET
Célimène -> PROPN
… -> PUNCT
ça -> PRON
ne -> ADV
compromet -> VERB
personne -> NOUN
! -> PUNCT
… -> PUNCT
Notre -> DET
Célimène -> NOUN
passait -> VERB
les -> DET
mains -> NOUN
dans -> ADP
les -> DET
cheveux -> NOUN
d’ -> ADP
un -> DET
grand -> ADJ
poète -> NOUN
… -> PUNCT
l’ -> DET
initiale -> NOUN
du -> ADP
poète -> NOUN
… -> PUNCT
faut -> VERB
toujours -> ADV
nommer -> VERB
un -> DET
poète -> NOUN
, -> PUNCT
sans -> ADP
ça -> PRON
on -> PRON
peut -> VERB
le -> PRON
confondre -> VERB
avec -> ADP
un -> DET
homme -> NOUN
qui -> PRON
fait -> VERB
des -> ADP
vers -> ADP
… -> PUNCT
Et -> CCONJ
tu -> PRON
entames -> VERB
le -> DET
dialogue -> NOUN
: -> PUNCT
« -> PUNCT
Ô -> PUNCT
mon -> DET
poète -> NOUN
! -> PUNCT
- -> PUNCT
fait -> VERB
la -> DET
Célimène -> PROPN
, -> PUNCT
- -> PUNCT
pourquoi -> ADV
ne -> ADV
faites -> ADJ
-vous -> PRON
plus -> ADV
de -> ADP
ces -> DET
charmantes -> NOUN
comédies -> NOUN
comme -> ADP
vous -> PRON
seul -> ADJ
savez -> VERB
en -> PRON
faire -> VERB
? -> PUNCT
… -> PUNCT
Pour -> ADP
un -> DET
rôle -> NOUN
de -> ADP
vous -> PRON
où -> PRON
j’ -> PRON
aurais -> VERB
quinze -> NUM
ans -> NOUN
, -> PUNCT
je -> PRON
donnerais -> VERB
ans -> NOUN
de -> ADP
ma -> DET
vie -> NOUN
! -> PUNCT
… -> PUNCT
» -> PUNCT
tu -> PRON
peux -> VERB
lâcher -> VERB
le -> DET
mot -> NOUN
: -> PUNCT
Célimène -> NOUN
, -> PUNCT
vous -> PRON
y -> PRON
auriez -> AUX
gagné -> VERB
! -> PUNCT
… -> PUNCT
et -> CCONJ
tu -> PRON
passes -> VERB
au -> ADP
poète -> NOUN
. -> PUNCT
Le -> DET
poète -> NOUN
a -> AUX
dîné -> VERB
; -> PUNCT
a -> AUX
ronflé -> VERB
pendant -> ADP
une -> DET
heure -> NOUN
tout -> ADV
seul -> ADJ
dans -> ADP
une -> DET
loge -> NOUN
de -> ADP
huit -> NUM
places -> NOUN
; -> PUNCT
est -> AUX
bu -> VERB
, -> PUNCT
mais -> CCONJ
bu -> VERB
… -> PUNCT
ferait -> VERB
un -> DET
poème -> NOUN
épique -> ADJ
, -> PUNCT
et -> CCONJ
parle -> VERB
nègre -> VERB
! -> PUNCT
Fais -> NOUN
- -> PUNCT
le -> DET
parler -> VERB
nègre -> NOUN
, -> PUNCT
le -> DET
public -> NOUN
adore -> VERB
ça -> PRON
, -> PUNCT
ça -> PRON
lui -> PRON
rappelle -> VERB
Paul -> PROPN
et -> CCONJ
Virginie -> PROPN
! -> PUNCT
- -> PUNCT
« -> PUNCT
Moi -> NOUN
… -> PUNCT
pièce -> NOUN
? -> PUNCT
… -> PUNCT
moi -> PRON
… -> PUNCT
comédie -> NOUN
? -> PUNCT
… -> PUNCT
travailler -> VERB
? -> PUNCT
… -> PUNCT
pas -> ADV
d’ -> DET
intérieur -> NOUN
? -> PUNCT
… -> PUNCT
impossible -> ADJ
! -> PUNCT
sale -> ADJ
… -> PUNCT
rien -> PRON
trouver -> VERB
… -> PUNCT
brosses -> NOUN
à -> ADP
dents -> NOUN
partout -> ADV
! -> PUNCT
… -> PUNCT
travailler -> VERB
! -> PUNCT
… -> PUNCT
trop -> ADV
sale -> ADJ
! -> PUNCT
… -> PUNCT
- -> PUNCT
Mais -> CCONJ
si -> SCONJ
quelqu’ -> PROPN
un -> DET
vous -> PRON
installait -> VERB
dans -> ADP
un -> DET
joli -> ADJ
petit -> ADJ
appartement -> NOUN
bien -> ADV
rangé -> VERB
? -> PUNCT
- -> PUNCT
Oh -> ADV
! -> PUNCT
… -> PUNCT
divin -> ADJ
… -> PUNCT
pas -> ADV
de -> DET
peignes -> NOUN
sur -> ADP
les -> DET
meubles -> NOUN
… -> PUNCT
intérieur -> NOUN
… -> PUNCT
plumes -> NOUN
taillées -> VERB
… -> PUNCT
une -> DET
pièce -> NOUN
! -> PUNCT
deux -> NUM
pièces -> NOUN
! -> PUNCT
… -> PUNCT
trois -> NUM
pièces -> NOUN
! -> PUNCT
… -> PUNCT
toujours -> ADV
! -> PUNCT
- -> PUNCT
À -> ADP
demain -> ADV
matin -> NOUN
… -> PUNCT
» -> PUNCT
- -> PUNCT
Et -> CCONJ
la -> DET
comédienne -> NOUN
serre -> NOUN
la -> DET
main -> NOUN
du -> ADP
poète -> NOUN
avec -> ADP
un -> DET
sourire -> NOUN
… -> PUNCT
tu -> PRON
trouveras -> VERB
le -> DET
sourire -> NOUN
! -> PUNCT
Le -> DET
poète -> NOUN
est -> AUX
exact -> ADJ
comme -> ADP
un -> DET
billet -> NOUN
. -> PUNCT
essaye -> VERB
un -> DET
fauteuil -> NOUN
: -> PUNCT
on -> PRON
y -> PRON
aurait -> AUX
dormi -> VERB
, -> PUNCT
- -> PUNCT
sans -> ADP
lire -> VERB
! -> PUNCT
… -> PUNCT
- -> PUNCT
Une -> DET
table -> NOUN
, -> PUNCT
du -> ADP
papier -> NOUN
blanc -> ADJ
, -> PUNCT
des -> DET
plumes -> NOUN
, -> PUNCT
de -> ADP
l’ -> DET
encre -> NOUN
… -> PUNCT
- -> PUNCT
« -> PUNCT
S’ -> SCONJ
y -> PRON
avait -> VERB
des -> DET
cigares -> NOUN
, -> PUNCT
soupire -> VERB
le -> DET
poète -> NOUN
, -> PUNCT
y -> PRON
aurait -> AUX
tout -> ADV
ce -> PRON
qu’ -> PRON
faut -> VERB
pour -> ADP
écrire -> VERB
. -> PUNCT
» -> PUNCT
Célimène -> PROPN
envoie -> VERB
chercher -> VERB
deux -> NUM
boîtes -> NOUN
de -> ADP
cigares -> NOUN
. -> PUNCT
L’ -> DET
heure -> NOUN
du -> ADP
déjeuner -> NOUN
arrive -> VERB
. -> PUNCT
« -> PUNCT
Ah -> PUNCT
! -> PUNCT
tenez -> VERB
, -> PUNCT
- -> PUNCT
dit -> VERB
le -> DET
poète -> NOUN
, -> PUNCT
- -> PUNCT
faut -> VERB
que -> SCONJ
je -> PRON
quitte -> VERB
vos -> DET
pantoufles -> NOUN
… -> PUNCT
et -> CCONJ
puis -> CCONJ
je -> PRON
déjeunerai -> VERB
avec -> ADP
des -> DET
amis -> NOUN
… -> PUNCT
nous -> PRON
causerons -> VERB
… -> PUNCT
impossible -> ADJ
… -> PUNCT
journée -> NOUN
perdue -> VERB
! -> PUNCT
- -> PUNCT
Mettez -> VERB
deux -> NUM
couverts -> NOUN
, -> PUNCT
- -> PUNCT
fait -> AUX
Célimène -> PROPN
à -> ADP
la -> DET
cantonade -> NOUN
, -> PUNCT
et -> CCONJ
se -> PRON
retournant -> VERB
: -> PUNCT
vous -> PRON
mangerez -> VERB
. -> PUNCT
Qu’ -> PRON
aimez -> VERB
-vous -> NOUN
? -> PUNCT
- -> PUNCT
Tout -> ADV
, -> PUNCT
sauf -> ADP
le -> DET
poulet -> NOUN
rôti -> ADJ
et -> CCONJ
le -> DET
vin -> NOUN
de -> ADP
Bordeaux -> PROPN
. -> PUNCT
» -> PUNCT
Le -> DET
soir -> NOUN
nouvelles -> ADJ
lamentations -> NOUN
du -> ADP
poète -> NOUN
: -> PUNCT
« -> PUNCT
Tenez -> VERB
! -> PUNCT
Si -> SCONJ
je -> PRON
m’ -> VERB
en -> PRON
vais -> VERB
chez -> ADP
moi -> PRON
, -> PUNCT
je -> PRON
n’ -> ADV
arriverai -> VERB
que -> SCONJ
demain -> ADV
, -> PUNCT
je -> PRON
me -> PRON
lèverai -> VERB
après-demain -> ADV
… -> PUNCT
et -> CCONJ
… -> PUNCT
- -> PUNCT
Allons -> PROPN
, -> PUNCT
voulez -> VERB
-vous -> PRON
que -> SCONJ
je -> PRON
vous -> PRON
fasse -> VERB
faire -> VERB
un -> DET
lit -> NOUN
dans -> ADP
le -> DET
salon -> NOUN
? -> PUNCT
- -> PUNCT
Non -> ADV
, -> PUNCT
j’ -> PRON
ai -> VERB
peur -> NOUN
la -> DET
nuit -> NOUN
, -> PUNCT
et -> CCONJ
vous -> PRON
? -> PUNCT
… -> PUNCT
» -> PUNCT
Bref -> ADV
, -> PUNCT
au -> ADP
bout -> NOUN
de -> ADP
huit -> NUM
jours -> NOUN
la -> DET
pièce -> NOUN
est -> AUX
faite -> VERB
. -> PUNCT
Elle -> PRON
est -> AUX
copiée -> VERB
. -> PUNCT
« -> PUNCT
Ah -> PUNCT
! -> PUNCT
- -> PUNCT
crie -> VERB
tout -> ADV
à -> ADP
coup -> NOUN
le -> DET
poète -> NOUN
, -> PUNCT
- -> PUNCT
un -> DET
ruban -> NOUN
! -> PUNCT
… -> PUNCT
un -> DET
ruban -> NOUN
pour -> ADP
l’ -> DET
amour -> NOUN
de -> ADP
Dieu -> PROPN
, -> PUNCT
un -> DET
ruban -> NOUN
pour -> ADP
l’ -> DET
amour -> NOUN
de -> ADP
moi -> PRON
, -> PUNCT
me -> PRON
faut -> VERB
un -> PRON
de -> ADP
vos -> DET
rubans -> NOUN
! -> PUNCT
Tenez -> VERB
, -> PUNCT
celui -> PRON
-là -> PRON
! -> PUNCT
… -> PUNCT
Oui -> ADV
, -> PUNCT
j’ -> PRON
ai -> VERB
l’ -> DET
habitude -> NOUN
comme -> ADP
cela -> PRON
de -> ADP
nouer -> VERB
mes -> DET
manuscrits -> NOUN
avec -> ADP
une -> DET
jolie -> ADJ
faveur -> NOUN
… -> PUNCT
une -> DET
idée -> NOUN
… -> PUNCT
c’ -> PRON
est -> AUX
bête -> ADV
… -> PUNCT
mais -> CCONJ
voilà -> VERB
. -> PUNCT
» -> PUNCT
Célimène -> PROPN
donne -> VERB
le -> DET
ruban -> NOUN
, -> PUNCT
fait -> VERB
la -> DET
rosette -> NOUN
, -> PUNCT
et -> CCONJ
le -> DET
poète -> NOUN
court -> ADJ
porter -> VERB
sa -> DET
pièce -> NOUN
à -> ADP
… -> PUNCT
parbleu -> NOUN
! -> PUNCT
à -> ADP
l’ -> DET
autre -> PRON
Célimène -> NOUN
du -> ADP
Théâtre -> NOUN
- -> NOUN
Français -> NOUN
! -> PUNCT
Maintenant -> ADV
, -> PUNCT
toi -> NOUN
, -> PUNCT
appelle -> VERB
ça -> PRON
: -> PUNCT
Roueries -> NOUN
d’ -> ADP
hommes -> NOUN
, -> PUNCT
sers -> VERB
chaud -> ADJ
, -> PUNCT
et -> CCONJ
- -> PUNCT
ça -> PRON
y -> PRON
est -> VERB
! -> PUNCT

In [90]:
df_final.to_csv("corpus_goncourt/1860_Charles Demailly_motif_pos.csv", index=False, encoding="utf-8")