# Import des modules nécessaires

In [11]:
import pandas as pd
import pathlib
import sys
import matplotlib.pyplot as plt
import numpy as np
import re
import spacy
from spacy.tokenizer import Tokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import LatentDirichletAllocation
from pathlib import Path
import sys
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import NMF

In [ ]:
nlp = spacy.load("fr_core_news_lg") # Charger le modèle de langue français de spaCy, qui inclut les vecteurs de mots pré-entraînés pour une meilleure analyse sémantique.

/Users/morganr/Champs_lexicaux_N-A/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
dossier_path = Path("/Users/morganr/Champs_lexicaux_N-A/corpus_goncourt") # Chemin vers le dossier contenant les fichiers .txt

donnees = [] # Liste pour stocker les données extraites de chaque fichier

# On boucle sur tous les fichiers .txt du dossier
for fichier in dossier_path.glob("*.txt"):
    with open(fichier, "r", encoding="utf-8") as f:
        contenu = f.read()
        
        # On ajoute les données extraites du fichier à la liste
    donnees.append({
            "nom_fichier": fichier.name, # Nom du fichier
            "texte_brut": contenu, # Contenu brut du fichier
        })
      
         

# Création du tableau de bord (DataFrame)
df = pd.DataFrame(donnees)
print(f"{len(df)} textes chargés avec succès.")

10 textes chargés avec succès.

In [ ]:
def segmenter_texte(text, taille=300): # On segmente le texte en segments de 300 mots
    mots = text.split()
    segments = []
    for i in range(0, len(mots), taille):
        segment = " ".join(mots[i:i+taille])
        if len(segment.split()) >= 100: 
            segments.append(segment)
    return segments

lignes = [] # Liste pour stocker les segments de texte avec leurs titres et IDs

for _, row in df.iterrows():
    titre = row["nom_fichier"] # On utilise le nom du fichier comme titre
    texte = row["texte_brut"] # On segmente le texte en segments de 300 mots
    segments = segmenter_texte(texte) # On ajoute chaque segment à la liste avec son titre et son ID
    
    for j, seg in enumerate(segments):
        
        
        lignes.append({ 
            "titre": titre, # Titre du texte (nom du fichier)
            "segment_id": j, # ID du segment (index du segment dans le texte)
            "texte_segment": seg # Contenu du segment de texte
        })

df_segments = pd.DataFrame(lignes)

df_segments

,titre,segment_id,texte_segment
0,1869_madame_gervaisais_travail.txt,0,"— Quarante scudi ? — Oui, signora. — Cela fait..."
1,1869_madame_gervaisais_travail.txt,1,"suivent… — Oui, signora… Nous, nous nous retir..."
2,1869_madame_gervaisais_travail.txt,2,et trempant la plume dans la boue d’un encrier...
3,1869_madame_gervaisais_travail.txt,3,"sa vie, Jules demandait à Edmond de lui en fai..."
4,1869_madame_gervaisais_travail.txt,4,place des touristes consciencieux lisaient le ...
...,...,...,...
2275,1864_renée_mauperin_travail.txt,219,"à son aise, dans son coin, la tête contre le m..."
2276,1864_renée_mauperin_travail.txt,220,disaient bientôt plus rien ; ils restaient mue...
2277,1864_renée_mauperin_travail.txt,221,trempaient dans la lumière le bord de leurs fe...
2278,1864_renée_mauperin_travail.txt,222,"cinq sous, des joujoux gagnés à des loteries, ..."
2279,1864_renée_mauperin_travail.txt,223,et emportent au ciel le visage des jeunes mort...

# Phase de traitement de textes

In [15]:
stop_word = {
    "bon", "bien", "tout", "toute", "tous", "toutes",
    "grand", "petit", "autre", "même", "seul",
    "faire", "aller", "venir", "voir", "dire", "savoir",
    "vouloir", "pouvoir", "falloir", "prendre", "mettre",
    "tenir", "donner", "parler", "trouver", "rester",
    "sembler", "penser", "avoir", "être",
    "chose", "fois",
    "monsieur", "madame", "mademoiselle", "mme", "mlle",
    "cher", "vrai", "renée", "croire",
}
# On peut ajouter d'autres stop words spécifiques au corpus ou à la langue française selon les besoins.

In [17]:
def nettoyer_texte(texte): #  Fonction pour nettoyer le texte : suppression des stop words, ponctuation, chiffres, espaces, et lemmatisation
    doc = nlp(texte) # Traiter le texte avec spaCy pour obtenir les tokens et leurs propriétés
    tokens = [] # Liste pour stocker les tokens nettoyés
    
    for token in doc:
        lemme = token.lemma_.lower()
        
        if (
            not token.is_stop # Ignorer les stop words (mots vides par défaut dans spaCy)
            and not token.is_punct # Ignorer la ponctuation
            and not token.like_num # Ignorer les chiffres
            and not token.is_space # Ignorer les espaces
            and token.pos_ in {"NOUN", "ADJ"} # Ne garder que les noms et adjectifs
            and len(token.lemma_) > 3 # Ne garder que les tokens dont la longueur du lemme est supérieure à 2 caractères
            and lemme not in stop_word
        ):
            tokens.append(lemme) # Ajouter le lemme du token en minuscules à la liste des tokens nettoyés
    
    return " ".join(tokens) # Retourner le texte nettoyé en joignant les tokens avec des espaces

df_segments["texte_nettoye"] = df_segments["texte_segment"].apply(nettoyer_texte) # Application de la fonction de nettoyage à chaque segment de texte

df_segments[["texte_segment", "texte_nettoye"]].head() # Affichage des 5 premiers segments avant et après nettoyage

,texte_segment,texte_nettoye
0,"— Quarante scudi ? — Oui, signora. — Cela fait...",scudi monnaie cent franc cent franc romaine ap...
1,"suivent… — Oui, signora… Nous, nous nous retir...",chambre fond besoin mère romaine vieux femme s...
2,et trempant la plume dans la boue d’un encrier...,plume boue encrier reçu étranger carte gervais...
3,"sa vie, Jules demandait à Edmond de lui en fai...",lecture haut mémoire idée manie matin soir fig...
4,place des touristes consciencieux lisaient le ...,place touriste consciencieux guide assiette so...

In [18]:
df_segments["nb_tokens_nettoyes"] = df_segments["texte_nettoye"].apply(lambda x: len(x.split()))
df_segments["nb_tokens_nettoyes"].describe()

count    2280.000000
mean       74.543860
std        17.306285
min        23.000000
25%        62.000000
50%        76.000000
75%        87.000000
max       121.000000
Name: nb_tokens_nettoyes, dtype: float64

In [19]:
vectorizer = TfidfVectorizer(
    min_df=5,
    max_df=0.8
    )

X = vectorizer.fit_transform(df_segments["texte_nettoye"])

X.shape

(2280, 4387)

In [ ]:
def afficher_topics(model, feature_names, n_top_words=10):

    for topic_idx, topic in enumerate(model.components_):
        top_words = [feature_names[i] for i in topic.argsort()[:-n_top_words - 1:-1]]
        print(f"Topic {topic_idx+1} : {' | '.join(top_words)}")
        
        
feature_names = vectorizer.get_feature_names_out()

for k in [8, 10, 12]:

    print(f"\n --NMF avec {k} topics--")

    nmf = NMF(n_components=k,
              init="nndsvda",
              random_state=42,
              max_iter=500
              )

    W = nmf.fit_transform(X)
    afficher_topics(nmf, feature_names, 10)

    print("Erreur :", nmf.reconstruction_err_)

 --NMF avec 8 topics--
Topic 1 : fille | jeune | père | maréchal | mariage | monde | année | salon | femme | amie
Topic 2 : ciel | arbre | soleil | ombre | lumière | jour | blanc | bois | terre | bleu
Topic 3 : sœur | malade | salle | interne | hôpital | médecin | jour | garde | voix | mort
Topic 4 : franc | argent | homme | journal | idée | lettre | atelier | cent | monde | dîner
Topic 5 : femme | amour | homme | pensée | cœur | esprit | parole | maîtresse | nature | passion
Topic 6 : main | tête | femme | oeil | bras | cheveu | corps | pied | noir | blanc
Topic 7 : frère | cirque | exercice | pied | tour | saut | directeur | aîné | jour | clown
Topic 8 : enfant | mère | fils | pauvre | père | jour | cœur | oeil | famille | maman
Erreur : 46.06103429626386

 --NMF avec 10 topics--
Topic 1 : enfant | mère | fils | pauvre | père | cœur | oeil | famille | jour | main
Topic 2 : ciel | arbre | soleil | ombre | bois | blanc | lumière | bleu | terre | noir
Topic 3 : sœur | malade | salle | interne | hôpital | voix | garde | médecin | service | main
Topic 4 : franc | argent | cent | pièce | affaire | homme | villacourt | porte | hôtel | ville
Topic 5 : heure | jour | temps | chambre | nuit | matin | mort | dîner | soir | journée
Topic 6 : main | tête | oeil | bras | cheveu | noir | blanc | pied | corps | robe
Topic 7 : frère | cirque | exercice | pied | tour | saut | directeur | aîné | clown | tonneau
Topic 8 : fille | jeune | père | maréchal | mariage | salon | monde | année | amie | petite
Topic 9 : homme | journal | livre | idée | esprit | talent | œuvre | monde | public | artiste
Topic 10 : femme | amour | homme | maîtresse | amant | cœur | mari | parole | créature | nature
Erreur : 45.90443077624188

 --NMF avec 12 topics--
Topic 1 : pensée | cœur | mort | parole | souffrance | amour | jour | idée | maladie | corps
Topic 2 : ciel | arbre | soleil | ombre | bois | blanc | lumière | bleu | terre | noir
Topic 3 : sœur | malade | salle | interne | hôpital | garde | médecin | voix | service | main
Topic 4 : enfant | mère | fils | pauvre | père | cœur | famille | jour | oeil | maman
Topic 5 : heure | jour | chambre | dîner | temps | matin | maison | nuit | porte | soir
Topic 6 : main | tête | oeil | bras | cheveu | noir | pied | blanc | corps | regard
Topic 7 : frère | cirque | exercice | pied | tour | saut | aîné | tonneau | clown | directeur
Topic 8 : fille | jeune | père | maréchal | mariage | monde | année | salon | amie | petite
Topic 9 : homme | journal | idée | talent | tableau | artiste | œuvre | monde | peintre | atelier
Topic 10 : femme | homme | amour | maîtresse | mari | amant | monde | ménage | créature | espèce
Topic 11 : théâtre | acteur | scène | pièce | rôle | tragédien | loge | directeur | français | voix
Topic 12 : franc | argent | cent | pièce | affaire | villacourt | rente | cochon | fruitière | noir
Erreur : 45.76033005937322

In [23]:
nmf = NMF(n_components=12, 
          random_state=42,
          init="nndsvda",
          solver="cd",
          max_iter=600,
          
          )
W = nmf.fit_transform(X)
H = nmf.components_


feature_names = vectorizer.get_feature_names_out()

def afficher_topics(model, feature_names, n_top_words=10):
    for topic_idx, topic in enumerate(model.components_):
        top_words = [feature_names[i] for i in topic.argsort()[:-n_top_words - 1:-1]]
        print(f"Topic {topic_idx+1} : {' | '.join(top_words)}")

afficher_topics(nmf, feature_names, 10)

Topic 1 : pensée | cœur | mort | parole | souffrance | amour | jour | idée | maladie | corps
Topic 2 : ciel | arbre | soleil | ombre | bois | blanc | lumière | bleu | terre | noir
Topic 3 : sœur | malade | salle | interne | hôpital | garde | médecin | voix | service | main
Topic 4 : enfant | mère | fils | pauvre | père | cœur | famille | jour | oeil | maman
Topic 5 : heure | jour | chambre | dîner | temps | matin | maison | nuit | porte | soir
Topic 6 : main | tête | oeil | bras | cheveu | noir | pied | blanc | corps | regard
Topic 7 : frère | cirque | exercice | pied | tour | saut | aîné | tonneau | clown | directeur
Topic 8 : fille | jeune | père | maréchal | mariage | monde | année | salon | amie | petite
Topic 9 : homme | journal | idée | talent | tableau | artiste | œuvre | monde | peintre | atelier
Topic 10 : femme | homme | amour | maîtresse | mari | amant | monde | ménage | créature | espèce
Topic 11 : théâtre | acteur | scène | pièce | rôle | tragédien | loge | directeur | français | voix
Topic 12 : franc | argent | cent | pièce | affaire | villacourt | rente | cochon | fruitière | noir

In [21]:
nmf = NMF(
    n_components=12,
    init="nndsvda",
    random_state=42,
    max_iter=500
)

W = nmf.fit_transform(X)

df_segments["topic_dominant"] = W.argmax(axis=1)
df_segments["poids_topic"] = W.max(axis=1)

In [22]:
for topic in sorted(df_segments["topic_dominant"].unique()):
    print(f"\n===== TOPIC {topic} =====")
    subset = (
        df_segments[df_segments["topic_dominant"] == topic]
        .sort_values("poids_topic", ascending=False)
        .head(5)
    )
    for _, row in subset.iterrows():
        print(f"\nTitre : {row['titre']} | Segment : {row['segment_id']} | Poids : {row['poids_topic']:.4f}")
        print(row["texte_segment"][:500])

===== TOPIC 0 =====

Titre : 1861_sœur_philomène_travail.txt | Segment : 32 | Poids : 0.1273
et s’amaigrissaient. Un malaise général, des souffrances qui se déplaçaient tous les jours lui donnaient continuellement un sentiment douloureux de toutes les parties de son corps, la conscience et la fatigue du jeu laborieux de ses organes, du travail de la vie dans son être. Elle était abattue en se levant, faible d’une faiblesse qu’elle ne pouvait surmonter. Quand elle montait des escaliers ou qu’elle courait, elle avait des battements de cœur : lui fallait s’asseoir. Le moindre travail lui d

Titre : 1882_la_faustin_travail.txt | Segment : 200 | Poids : 0.1234
elle mangerait, elle n'aurait plus son visage en face d'elle ; et, quand elle dormirait, elle n'aurait plus son sommeil lié au sien ; et elle n'aurait plus sa parole pour dire la même pensée que celle venue au même moment dans sa tête ; et elle n'aurait plus ses yeux pour voir, pour voir à deux... Non, plus rien désormais dans sa vie que l'épouvantable solitude, en un monde vide, aux jours n'ayant plus de soleil, aux choses n'ayant plus de Joie pour elle. Si encore elle avait été préparée à la t

Titre : 1869_madame_gervaisais_travail.txt | Segment : 58 | Poids : 0.1153
« Foi et hystérie (Zola, les Goncourt ) ». Ce chant, cette voix qui avait fini par l’ineffable note mourante et crucifiée, le Lamma sabachtani du Golgotha, laissaient à Mme Gervaisais un long écho qu’elle emportait, une vibration dont le tressaillement aux endroits sensibles de son être, montait jusqu’à ses lèvres qui, d’elles-mêmes, tout bas en répétaient le soupir suprême. Et en même temps, avec cette mémoire intérieure, elle sentait s’élever et remonter peu à peu en elle tout le douloureux de

Titre : 1865_germinie_lacerteux_travail.txt | Segment : 213 | Poids : 0.1122
qu’on eût dit prêts à une confession, de mouvements de lèvres au bord desquelles semblait trembler un secret. Elle retrouvait, avec ces yeux qu’on a pour ceux qui ne sont plus, les regards si tristes de Germinie, des gestes, des poses qu’elle avait, ses visages de désespoir. Et elle devinait là-dessous maintenant des blessures, des plaies, des déchirements, le tourment de ses angoisses et de ses repentirs, les larmes de sang de ses remords, toutes sortes de souffrances étouffées dans toute sa vi

Titre : 1861_sœur_philomène_travail.txt | Segment : 37 | Poids : 0.1122
accroissement de ferveur. Donnant à la prière tout le temps qu’elle pou vait, elle en prolongeait l’élévation et l’écho intérieur, en en gardant pendant son travail le murmure au bord de ses lèvres et la pensée au fond de ses pensées. Pendant les récréations, elle faisait des lectures d’édification. Elle se confessait, elle communiait toutes les fois que l’approche des sacrements lui était permise. Elle avait, à la messe et aux vêpres de Saint-Laurent, des recueillements qui éloignaient d’elle l

===== TOPIC 1 =====

Titre : 1860_Charles Demailly_travail.txt | Segment : 280 | Poids : 0.2547
là, les ricochets de feu le long des troncs de saules et des estacades, la ligne de feu qui lignait le bord d’une nacelle, la raie de feu d’un jonc droit dans l’eau. Ils descendaient, ils remontaient, effleurant les sables amassés à fleur d’eau dont les creux gardent une eau dormante et chaude ; ils passaient sur les roseaux ondulant et toujours saluant l’eau, découvrant, au milieu des forêts d’herbes aquatiques, des passages et des sinus mystérieux où l’eau était bleue comme le bleu du linge. I

Titre : 1869_madame_gervaisais_travail.txt | Segment : 98 | Poids : 0.2308
Castel Gandolfo, où elle avait résolu de passer, cette année-là, les chaleurs du mois de juillet et d’août. L’enfant partait avec le bonheur des enfants à changer de place, tout à la fois sérieux et les yeux souriants. La voiture quittait les murs brûlants de Rome et entrait dans la campagne sèche et roussie, tachée çà et là de places noires, pareilles à des endroits brûlés. De lourds bœufs marchaient dans des lits de ruisseaux taris, portant leurs grandes cornes avec la majesté de cerfs lassés

Titre : 1865_germinie_lacerteux_travail.txt | Segment : 65 | Poids : 0.2306
de femmes, d’enfants, mangeaient des pommes de terre frites, des moules et des crevettes, et ils arrivaient au premier champ, à la première herbe vivante : sur le bord de l’herbe, y avait une voiture à bras chargée de pain d’épice et de pastilles de menthe, et une marchande de coco vendait à boire sur une table dans le sillon… Étrange campagne où tout se mêlait, la fumée de la friture à la vapeur du soir, le bruit des palets d’un jeu de tonneau au silence versé du ciel, l’odeur de la poudrette à

Titre : 1865_germinie_lacerteux_travail.txt | Segment : 61 | Poids : 0.2233
plus sous les doigts le tintement et le frétillement. Quand le printemps fut venu : — Si nous allions à l’entrée des champs ? disait presque tous les soirs Germinie à Jupillon. Jupillon mettait sa chemise de flanelle à carreaux rouges et noirs, sa casquette en velours noir ; et ils partaient pour ce que les gens du quartier appellent « l’entrée des champs. » Ils montaient la chaussée Clignancourt, et avec le flot des Parisiens de faubourg se pressant à aller boire un peu d’air, ils marchaient ve

Titre : 1867_manette_salomon_travail.txt | Segment : 259 | Poids : 0.2202
et une solennité de monuments, beaux de la beauté sacrée des siècles, sortant, comme d’une herbe naine, des forêts de fougère écrasées de leur hauteur : le matin jouait sur leur rude écorce, leur peau centenaire, et passait sur leurs veines de bois les blancheurs polies de la pierre. Coriolis se mettait à marcher sous ces voûtes qui éclataient, au-dessus de lui, à des élévations de cent pieds, en fusées de branches, en cimes foudroyées, en furies échevelées et tordues, ayant l’air de couronnes d

===== TOPIC 2 =====

Titre : 1861_sœur_philomène_travail.txt | Segment : 88 | Poids : 0.2952
ramenait ainsi propre et peigné au lit de la malade qui avait pour la sœur le regard qu’elle aurait eu pour la Sainte Vierge, si elle lui était apparue avec la main de son fils dans la sienne. La femme allait s’épuisant. Un jour l’enfant était auprès d’elle sur la chaise. la regardait presque effrayé, cherchant sa mère dans ce visage où ne la retrouvait plus. La sœur essayait de le distraire en le caressant. Barnier, au pied du lit, posait sous le drap des sinapismes sur les jambes de la malade.

Titre : 1861_sœur_philomène_travail.txt | Segment : 96 | Poids : 0.2821
avec de tout petits bras... et dans l’autre une petite fille... ça doit être une grande fille à présent... Elle avait des cheveux roux, ainsi ce n’est pas difficile.,. Vous regnrderez au quatrième... Je pleurerais de revoir les fenêtres... — dit la sœur comme se parlant à elle-même. — J’y ai été toute petite, — reprit-elle après un moment de rêverie en revenant à l’interne. Parfois l’interne était en veine de taquinerie. Ces jours-là s’amusait à tourmenter la sœur Philomène sur la religion. argu

Titre : 1861_sœur_philomène_travail.txt | Segment : 81 | Poids : 0.2794
c’est de travailler : on ne s’ennuie pas. — Ça m’a l’air joliment beau, dites donc, ce que vous faites là... une broderie, excusez... pour quelque princesse, hein ? — Je vais vous dire... — dit la malade après avoir regardé si la sœur Philomène s’éloignait. — C’est pour un cadeau... Voyez-vous, c’est une bande de jupon... Comme voilà déjà six mois que je suis ... . Barnier m’a si bien soignée... j’ai pensé à lui donner un petit souvenir... Ce garçon-là est trop gentil pour n’avoir pas une petite

Titre : 1861_sœur_philomène_travail.txt | Segment : 139 | Poids : 0.2594
aux tempes une bouffée. de feu. La sœur, retournée, faisait tiédir une tisane refroidie. la saisit par les deux bras, approcha d’elle ses lèvres ; mais la sœur dénoua d’un effort suprême ses poignets de l’étreinte qui voulait la lier, et Barnier fut frappé au visage. Une seconde, eut envie de rendre le coup, puis eut peur de lui... traversa la salle, descendit l’escalier, tomba assis au bas du perron, sur le mur qui entoure le préau des malades ; et la, prenant une poignée de la neige dans laque

Titre : 1861_sœur_philomène_travail.txt | Segment : 133 | Poids : 0.2495
à travers la première fumée des pipes qui s’allumaient. Au moment où la bouteille d’eau-de-vie, circulant de mains en mains pour le gloria, passait au-dessus de la tête de Barnier, Barnier qui n’y touchait jamais la saisit et remplit à moitié sa tasse vide. — Les sœurs ?... les sœurs... avec cela, — disait en ce moment une petite voix aiguë à l’autre bout de la table, — je te dis que j’ai eu une maîtresse qui est allée accoucher à l’hôpital. Eh bien ! elles ne la changeaient pas... elles la lais

===== TOPIC 3 =====

Titre : 1869_madame_gervaisais_travail.txt | Segment : 182 | Poids : 0.3281
mon Dieu ! comment voulez-vous que je l’aime ? — Broyez votre cœur… Votre enfant ?… un enfant marqué au front des signes de la colère de Dieu, l’enfant puni, maudit de votre incrédulité d’alors… La mère voulut encore essayer d’élever la voix. Mais le confesseur l’écrasa avec ces mots : « Si quelqu’un vient à moi, et qu’ ne haïsse pas son père, sa mère, son épouse, ses enfants… ses enfants ! entendez-vous ?… ne peut être mon disciple. » Ce sont les paroles mêmes de Notre-Seigneur, Jésus-Christ, a

Titre : 1869_madame_gervaisais_travail.txt | Segment : 87 | Poids : 0.2992
pas ? N’est-ce pas que tu veux bien lire… dans ce beau livre-là ? Et l’enfant se penchant et se ramassant sur la page du livre ouvert, presque assis sur ses jarrets pliés, comme s’ rassemblait et concentrait toute sa personne en attention pour en faire sortir ce que sa mère lui demandait : — Allons ! ce n’est pas si difficile… reprenait Mme Gervaisais. Et puis, tu aimes tant petite mère ?… Tiens ! rien que jusque-là… Et la leçon s’arrêtait dans les effusions du pauvre enfant qui ne pouvait toujo

Titre : 1864_renée_mauperin_travail.txt | Segment : 38 | Poids : 0.2588
de tout, le plus intelligent, le plus beau et surtout le plus distingué des hommes. était myope et portait un lorgnon : elle ne voulait même pas convenir qu’ eût la vue basse. Quand était là, elle le regardait parler, s’asseoir, marcher ; elle lui souriait, quand avait Je dos tourné. Elle aimait les plis de son habit. Quand n’était pas là, elle restait souvent des minutes enfoncée dans un fauteuil : une idée d’une douceur infinie éclairait et apaisait peu à peu son visage ; de l’ombre, de la pai

Titre : 1867_manette_salomon_travail.txt | Segment : 39 | Poids : 0.2585
aux yeux bleus. — Oh ! charmante… dit Coriolis ; et faisant signe à l’enfant : — Viens un peu, petite… Un peu poussée par sa mère, un peu attirée par le monsieur, et marchant vers son regard, moitié peureuse et moitié confiante, elle arriva à lui. Coriolis, la mettant sur ses genoux, lui fit prendre des gâteaux dans des assiettes, sur la table. Puis lui passant la main dans ses petits cheveux, des cheveux d’enfant blonde qui sera brune, et s’amusant les doigts de ce chatouillement de soie, resta

Titre : 1869_madame_gervaisais_travail.txt | Segment : 196 | Poids : 0.2269
toujours quelque chose de toi, au moins !… Ah ! ton séjour d’ !… — Voilà… on t’a écrit de Rome… . Flamen de Gerbois… que sais-je ? peut-être Honorine… On t’aura donné des préventions… — Des préventions ? Et se levant : Des Préventions ! Mais n’y a qu’à te voir, qu’à t’entendre, pauvre chère sœur !… Voyons, est-ce que tu ne viens pas de me dire que tu as rompu avec toutes tes amitiés ? Et se mettant à marcher, du canapé à la fenêtre, dans une promenade qui revenait toujours sur elle, lui jetait p

===== TOPIC 4 =====

Titre : 1865_germinie_lacerteux_travail.txt | Segment : 59 | Poids : 0.1728
Un jour, en entrant dans la cuisine de Germinie, mademoiselle vit un peu de terre dans une boîte à cigares posée dans le plomb. — Qu’est-ce que c’est ça ? lui dit-elle. — C’est du gazon… que j’ai semé… pour voir, fit Germinie. — Tu aimes donc le gazon maintenant ?… ne te manque plus que d’avoir des serins ! Au bout de quelques mois, la vie, toute la vie de Germinie appartint à la crémière. Le service de mademoiselle n’était guère assujettissant et lui prenait bien peu de temps. Un merlan, une cô

Titre : 1865_germinie_lacerteux_travail.txt | Segment : 197 | Poids : 0.1527
elle ne disait rien, et recommençait à regarder au même endroit, dans le vide, devant elle, fixement, éternellement. Quand mademoiselle rentrait de chez l’amie où elle allait dîner, elle trouvait Germinie dans l’obscurité, sans lumière, affaissée dans un fauteuil, les jambes allongées sur une chaise, la tête penchée sur sa poitrine, et si profondément absorbée, que parfois elle n’entendait pas la porte s’ouvrir. Dans la chambre, en avançant, semblait à Mlle de Varandeuil déranger un épouvantable

Titre : 1884_cherie_travail.txt | Segment : 189 | Poids : 0.1434
chargé d'inspecter les places fortes du nord de la France, eût fort étonné la jeune fille! Aussitôt après déjeuner, elle sortait suivie de sa femme de chambre, et allait, aux quatre coins de Paris, acheter dans les magasins de nouveautés les plus distants, les plus éloignés l'un de l'autre, pour quelques sous de fil, de coton, de passementerie. Elle qui ne faisait pas autrefois un pas dans Paris sur ses pieds, qui était toujours en voiture, elle marchait tout le temps. Elle marchait volontaireme

Titre : 1860_Charles Demailly_travail.txt | Segment : 186 | Poids : 0.1254
Les femmes y naissent provinciales, c’est tout dire… Un pays impossible, inventé par les sous-préfets, et où y a des gens qui devinent les rébus de L’Illustration ! Je n’exagère rien. – Avez-vous jamais songé à cette chose horrible qui peut être : un receveur des contributions sans vocation ?… Mais non, cela n’est pas : y a un Dieu. « Je me dis ennuyé, mon cher Chavannes ; mais, au fond, je suis triste. Me voilà tout seul dans la vie. Je n’ai plus que des parents à je ne sais combien de degrés,

Titre : 1877_la_fille_elisa_travail.txt | Segment : 72 | Poids : 0.1246
Élisa remarquait alors que tous ces paquets portaient sur un morceau de peau quelque chose d'écrit ; elle s'approchait de plus près, lisait sur l'un d'eux : No . Entrée – le mars . Sortie – le mars . Ces deux dates… ça représentait bien des années… mais au juste, combien d'années ça faisait- ? Et comme dans le vide de sa cervelle, dans la défaillance et l'espèce d'évanouissement de son être, elle ne trouvait pas tout de suite, Élisa se mettait à compter sur ses doigts : , , , , , … Mais, au mili

===== TOPIC 5 =====

Titre : 1864_renée_mauperin_travail.txt | Segment : 102 | Poids : 0.1688
la rampe, les yeux de madame Bourjot. Cependant Renée arrivait déguisée en bailli de village ; n’y avait plus qu’à signer le contrat : Pierrot prenant la main de celle qu’ aimait, se mettait à dire tout le bonheur qu’ allait avoir avec elle… La femme qui était à côté de madame Bourjot la sentit un peu peser sur son épaule. Henri acheva sa tirade, la pièce se dénoua et finit. Tous les gants blancs étaient en l’air, toutes les mains battaient. Tout à coup la voisine de madame Bourjot vit quelque c

Titre : 1867_manette_salomon_travail.txt | Segment : 192 | Poids : 0.1616
se mêlait la coupe fière de profil des peuples de désert à des humilités louches de commerces douteux de grande ville, des teints plombés tout à la fois par un ancien soleil et par une réverbération de vieil argent, des jeunes gens aux cheveux laineux, à la tête de bélier, des figures à cheveux papillotés, à gros diamant faux sur la chemise, étalant ce luxe de velours gras qu’aiment les marchands de choses suspectes, de petits yeux allumés de la fièvre du lucre, et des sourires d’Arabes dans des

Titre : 1860_Charles Demailly_travail.txt | Segment : 216 | Poids : 0.1602
le sommeil éveillé de leur bonheur : une envolée d’étoiles jaillissant de la bûche leur jetait en montant ses lueurs à la face ; puis l’ombre et le silence leur revenaient aux joues et aux lèvres… Enfin sonnait le coucher. Le déshabillé lent et plein de retards, la toilette de nuit, épingle à épingle, les vêtements qui tombent à regret, le fichu qu’une main enlève et qu’une autre main défend, cette jolie pudeur de minuit qui regarde ses défaites dans la glace et fait des nœuds au lacet de son co

Titre : 1865_germinie_lacerteux_travail.txt | Segment : 105 | Poids : 0.1532
pour toute la vie !… Excusez ! Ah ! bien merci… C’est moins cher de vous le rendre, votre argent… Le reste d’un garçon de café !… mon pauvre cher enfant !… Dieu l’en préserve ! Germinie avait arraché de la patère son châle et son chapeau. Elle était dehors. Mademoiselle était assise dans son grand fauteuil au coin de la cheminée où dormait toujours un peu de braise sous les cendres. Son serre-tête noir, abaissé sur les rides de son front, lui descendait presque jusqu’aux yeux. Sa robe noire, en

Titre : 1867_manette_salomon_travail.txt | Segment : 222 | Poids : 0.1508
yeux, dans la tête, cette femme en blouse, jetée sur les pavés, et qui semblait le Génie de l’émeute en Titi. Coriolis détestait ce portrait. n’y trouvait pas seulement le souvenir blessant d’un autre ; y reconnaissait encore malgré lui, et tout en voulant se le nier, une ressemblance mauvaise, une expression de quelque chose qu’ n’aimait pas à voir, et qui semblait se mettre entre lui et Manette, quand regardait Manette après avoir regardé la toile. avait essayé vainement de décider Manette à s

===== TOPIC 6 =====

Titre : 1879_frères_zemganno_travail.txt | Segment : 47 | Poids : 0.2756
» le lendemain Nello mettait la balle dans le creux de sa main, donnait le coup de poing, jetait à terre son persécuteur. Ce coup de poing, l’eùt donné à Rabastens aussi bien qu’au méchant gamin, si son frère lui avait désigné l’Alcide. Et pour tout en était de même. Une autre fois Giarini, en veine de plaisanterie, événement rare, s’étant amusé à accuser Nello d’avoir déferré Lariflette ; en dépit de sa presque certitude que les chiens n’étaient point ferrés, le cadet ébranlé par le sérieux du

Titre : 1879_frères_zemganno_travail.txt | Segment : 163 | Poids : 0.2600
temps s’écoulait, sans amener même le jour où Nello pouvait enfin se passer de ses béquilles, c’étaient chez le jeune frère des absorptions, des concentrations, des abîmements muets, avec, sur sa douce figure qui avait désapris le sourire, quelque chose d’inexprimablement douloureux. Comme enfoncé et perdu tout au fond de lui, Nello avait maintenant, lorsque son frère venait à lui parler, un « hein ? » qui était comme l’éveil, le retirement d’un homme d’un mauvais rêve. Et presque jamais plus, n

Titre : 1879_frères_zemganno_travail.txt | Segment : 162 | Poids : 0.2597
taquiner, aussi pressé que toi, va.... et voilà au moment que ça y était.... eh bien, voilà, que c’est fini pour moi... les bravos ! » Alors se retournant brusquement et prenant les mains de son frère : « Mais, tu le sais bien, disait Nello avec une intonation de caresse, je resterai heureux des tiens, ce sera toujours ça..... » Et Nello ne lâchait pas les mains de Gianni qu’ pressait, comme s’ avait à lui faire une confidence qui avait de la difficulté à sortir de sa bouche. « Frère, — soupirai

Titre : 1879_frères_zemganno_travail.txt | Segment : 161 | Poids : 0.2574
accroché à une patère. Gianni se leva pour allumer une bougie. « Laisse nous encore là dedans, » fit Nello. Gianni vint se rasseoir près de son frère et se remit à lui parler de nouveau, voulant enfin obtenir de Nello une parole qui espérât dans l’avenir, dans un avenir même lointain. « Non, — c’était Nello qui interrompait son frère tout à coup, — je sens que je ne pourrai plus jamais travailler... plus jamais entends-tu, plus jamais... Et le désespéré « plus jamais » répété par le jeune frère,

Titre : 1879_frères_zemganno_travail.txt | Segment : 105 | Poids : 0.2564